In [4]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import pickle

In [6]:
df = pd.read_csv("homeprices.csv")
df.head()
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [7]:
model.predict([[5000]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

## pickle lib

In [12]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [14]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [16]:
mp.predict([[5000]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

## joblib library

In [24]:
import joblib
joblib.dump(model, 'model_joblib')
mj = joblib.load('model_joblib')

In [25]:
mj.predict([[5000]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])